Add cloudlet lifetime feature
manoelcampos/cloudsimplus pull request #375
Opened 2021-12-23 13:51 UTC by sun-lingyu

#### What's this Pull Request does, clear and precisely?
This pull request added `lifeTime` attr and several related methods for a cloudlet. Users can use `setLifeTime()` method to set it, and when it is set, the cloudlet will finish execution after `lifeTime`  after its execution starts. 

#### Where should the reviewer start?
You can start from `CloudletSchedulerAbstract.java`.

#### Are there some simulation examples to show the performed changes working?
This pull request added a example(`PlanetLabExample2`)  to demonstrace its usage.

#### What are the relevant issue ticket numbers?
373

#### The issues or features included were discussed elsewhere outside github? If yes, please provide the links.
Nothing.

#### Any additional information you want to provide?
Currently lifetime can only be greater than `datacenter.SchedulingInterval`. Otherwise the cloudlet will finish after `datacenter.SchedulingInterval` has passed. Future work is needed to find out the reason and fix it.

2021-12-23 18:40 UTC, manoelcampos commented
Helo @sun-lingyu 
Thanks for that.
I have to review it. Taking a quick look, there are some small things that need to be updated.
Since holidays are knocking on the door, I don't think we'll be able to complete the review and merge the changes before that. I'll make some small changes by now and try to provide some feedback.

Thanks for you contribution.

2021-12-23 22:01 UTC, manoelcampos requested changes
Hey @sun-lingyu,

I've made lots of small changes. Check the commits for details.
There are some other small issues I spotted in a quick review.
I won't be able to perform a new review round in the next days,
but I'll do it ASAP.

2021-12-23 22:04 UTC, manoelcampos commented on cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/traces/PlanetLabExample2.java
> + * @author Manoel Campos da Silva Filho
You can add your name here

2021-12-23 22:05 UTC, manoelcampos commented on cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/traces/PlanetLabExample2.java
> +public class PlanetLabExample2 {
The name of the class could be `PlanetLabCloudletLifeTimeExample`.
This numbering in examples were used in the beginning, but currently I'm trying to use more meaningful example names.

2021-12-24 03:05 UTC, sun-lingyu commented
@manoelcampos 
Thank you very much!! 
As a beginner, I've really learnt a lot. 
Wish you a happy holiday:)

2021-12-24 12:53 UTC, manoelcampos commented
Great. Happy holidays. I'll carry the review on soon.

2022-05-26 20:27 UTC, manoelcampos approved these changes

2022-05-26 20:34 UTC, merged

2022-05-26 20:38 UTC, manoelcampos commented
Hey @sun-lingyu 
I'm really sorry for the very late reply.
I was away from the project for a few months but I'm back.

After reviewing your PR, I realized there were lots of issues with time attributes scattered across multiple classes such as Clodlet, CloudletExecution, and CloudletDatacenterExecution. There was a TODO comment in this last class, explaining some of the issues which were inherited from CloudSim. Those duplicated attributes were causing data inconsistency and were the source of many bugs.

Since you were dealing with a new time attribute that was suffering from those issues, I had to fix them.
Check the last commit comment for more details. 
Thanks for you initial work.